import { SafeHtml } from "@/components/SafeHtml";
import { useEffect } from "react";
import { Link } from "react-router-dom";

const KashmirNahmad = () => {
  useEffect(() => {
    document.body.style.backgroundColor = "#E7FFDF";
    document.body.style.backgroundImage = "url('/barks/slate3.gif')";
    document.body.style.color = "#000000";
    return () => {
      document.body.style.backgroundColor = "";
      document.body.style.backgroundImage = "";
      document.body.style.color = "";
    };
  }, []);

  const htmlContent = `

<CENTER>

<IMG src="/graph/fdline5.gif" WIDTH=350 HEIGHT=4 VSPACE=6><BR>
<FONT  SIZE=+2 COLOR=#007339><STRONG><EM>FDL-AP Archives</EM></STRONG></FONT><BR>
<IMG src="/graph/fdline5.gif" WIDTH=350 HEIGHT=4>
<BR><BR>
<TABLE  ALIGN=left BORDER=3 HSPACE=15 VSPACE=15 CELLPADDING=3 CELLSPACING=3>
<TR><TD ALIGN=MIDDLE><IMG SRC="/graph/nishatc5.jpg" ALT="Lt. Gen. Nishat Ahmad" WIDTH=167 HEIGHT=220 BORDER=2 ></TD></TR>
</TABLE>


<HR WIDTH=300 ALIGN=CENTER SIZE=3>
<H2>SETTLING KASHMIR</H2>
<FONT  SIZE=+1><STRONG>Prospects for Peace, Justice, Independence...</STRONG></FONT><P>
<HR WIDTH=200 ALIGN=CENTER SIZE=2>
<H3>Interview with Lt. Gen. (Retd)  Nishat Ahmad </H3>
<strong>Director, Institute of Regional Studies, <BR>Islamabad, Pakistan</STRONG><BR><BR>
<HR WIDTH=300 VSPACE=10 ALIGN=CENTER SIZE=3>
<P>

</CENTER>
<BR><BR><BR>

<H4>AS: The peaceful settlement of the Kashmiri issue seems to hinge on the implementation of the UN Security Council Resolutions of 1948 and 1949 which called for a state-wide plebiscite. Why do you think that after nearly 50 years, nothing has really been done to make this occur?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>Lt. Gen. Nishat Ahmad</STRONG>: There are two aspects that I think we need to consider. One, of course, involves those that are concerned with the implementation of the UN Security Council Resolution -- and this is primarily the major Western powers -- and the other involves those that are concerned with implementation at the site, and that is India and Pakistan. Now, when you look at the history you will find that the United Nations initially sent a number of very senior diplomats to suggest how the plebiscite could be conducted, and there were a number of recommendations that were made at various periods of time. I don't want to go into the details of each one, but in general, I would say that every time a major recommendation came from a UN appointed plebiscite administrator, Pakistan accepted and India rejected. <P>

From the Indian point of view, after having gone to the United Nations for this solution for Kashmir, they found their purpose of having Pakistan declared an aggressor was not achieved. In fact, the United Nations, through its Security Council, came back with a very objective and very fair resolution that was that the people of Kashmir ought to decide which state they want to join. Now, having been saddled with that resolution, India now wanted to back out of it and they found that it was not too difficult given the fact that they were in control of much of the State. All they had to do was refuse to implement it and they would continue to be in control of the State. So, this is the basic reason why the resolutions have not been implemented. <P>

The United Nations is not in the business of enforcing its resolutions, where the policies of one of the superpowers is not involved. The United Nations would be willing to enforce the resolution in a place like Iraq because the United States wants it. It won't happen in case of Kashmir, and Kashmir is not the only exception. I think there are about 1000 resolutions in the UN Security Council, and I am told -- I may be slightly inaccurate here -- but there are only 6 to 8 which have been implemented. So, that is the record of the UN Security Council. If the United States in the present situation, or if the five permanent members in the previous scenario, wanted a resolution to be implemented and all five agreed, then it would have been implemented. But that was not the case in the Kashmir resolution, and you therefore find that implementation is held back. But the basic reason is that India knew that any implementation of the resolution would go against it. So, all it has done is stonewall the implementation of the resolutions. </FONT></BLOCKQUOTE><P>

<H4>AS: Why has Pakistan not done more in terms of military support in the Jammu-Kashmir area?</H4>

<BLOCKQUOTE><FONT  SIZE=+1>AN: Pakistan firmly believes that the solution to a political problem is not through military means, that we ought to get a political situation resolved, even an international political situation resolved, through dialogue. Our efforts have been to get the Indians to enter into dialogue with us, and to also enter into a dialogue with the Kashmiris, who are the main people affected; and through dialogue reach a solution. The United Nations itself when it wants its resolutions implemented, it will want these implemented through the willing cooperation of the participants rather than force the implementation through military force. I don't think, with the exception of the Gulf War, the United Nations has used force to enforce its resolutions anywhere. And I think Kashmir again is a situation where peaceful negotiations, credible negotiations, fruitful negotiations should lead to the solution of the problem. I don't think the military confrontation is a solution.</FONT></BLOCKQUOTE>

<H4>AS: There's also talk of Prime Minister Sharif being in favor of further normalization of relations with India, and he has made many overtures to India. The Opposition Party Chairperson Benazir Bhutto is accusing the present regime of possibly going too far in its efforts. How far do you think the Prime Minister should go?</H4>

<BLOCKQUOTE><FONT  SIZE=+1>AN: I think he should go as far as the Indians are willing to come. They should meet us halfway. Having had this problem now unresolved for the last fifty years, with Pakistan and India having gone to war at least twice over the Kashmir problem itself, the third war was over East Pakistan, but the two major wars between India and Pakistan were about Kashmir. I think both the Indians and the Pakistanis have come to realize that a third war or military confrontation is still not going to lead to a solution. So, we need to discuss the problem through a mutual dialogue, put our points of view across, and then try to reach an understanding. Pakistan, of course, has gone on to say that it is willing to accept mediation, arbitration or whatever assistance the other international organizations or individual countries are willing to give, because we think our case is just and therefore, we do not stand to lose anything if we have an outsider - a neutral, objective observer, whether it's the United States or the European Union or the United Kingdom, which of course is much more knowledgeable about this situation since they were the rulers at the time of independence -- that any of these countries would be acceptable to us, either as a mediator or as an arbitrator. It is the Indians who every time have refused it, because they know that any mediation or arbitration which is based on a fair and just settlement is likely to go against them. Since they are unwilling to accept outside mediation or arbitration, therefore, our only peaceful recourse is to have a bilateral dialogue. And I think PM Nawaz Sharif is quite right in trying to do as much as he can to move forward in terms of a bilateral dialogue. So, that we don't remain stuck in this present straitjacket for all time to come.</FONT></BLOCKQUOTE>

<H4>AS: Objectively speaking, what concessions do you think Pakistan must make toward realizing normalization?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: They expect us to increase trade, to increase political as well as normal interaction between India and Pakistan. Pakistan is willing to do that as long as the basic issue which is the cause of all of our mutual difficulties is resolved and that is the issue of Kashmir. At least it is to be talked about as candidly as we talk about trade and other issues. During the three rounds of discussions that we had, in the second round the Indians agreed to discuss Kashmir substantively in a separate group, but unfortunately during the third round they backed out. So we're stuck in that situation. We are now waiting for the elections to take place because there is no point discussing this issue with the present government which may not be there next month. This next round of talks is likely to take place after the new Indian government comes to power, after it announces what its policy is going to be vis a vis the India-Pakistan dialogue.</FONT></BLOCKQUOTE>

<H4>AS: Is Pakistan somewhat apprehensive if the BJP is sworn into office?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I'm not sure that apprehensive would accurately describe this, but I read of the BJP that it is basically a fundamentalist organization whose anti-minority stand about the Indian minorities is quite well known; that it is fairly chauvinistic in its approach towards even the internal situation in India, and therefore I think we are going to have a difficult time establishing a normal working relationship with that government. But this is surely speculative at the moment.<P>

When any political party comes to power, it realizes that all that it has said while it was out of power, it cannot all be implemented when it comes to power. In other words, the reality of governance forces most political parties to moderate many of the things that they said when they were out of power. It is my feeling that the BJP will also be affected by this phenomenon, that it will have to moderate a lot of the policies that it has been declaring as part of its manifesto while it is out of power. <P>

For example, one of the things that it has categorically said is that it will overtly go nuclear. It is all right to say that you will go overtly nuclear when you are out of power because you don't have the responsibility of making India a nuclear-weapon state. But when you are the government, you also have to consider the consequences of going overtly nuclear, not only vis a vis Pakistan, but vis a vis the rest of the world. The same is the case with the removal of Clause 370 of the Indian Constitution which deals with the special status of Kashmir. They said they will do away with this clause. If this is going to increase the level of opposition that the Indian Security Forces in Kashmir face at the moment to a much higher level, then they will also consider whether the advantage that they might gain by removing that clause from the Constitution will offset the disadvantages of a much higher level of resistance from the Kashmiri population, a much more dissatisfied Kashmiri population. They have to consider this.<P>

The third major element that they have talked of is the uniform civil code. Now, the Indian Constitution, as well as the previous Indian governments, has always given this assurance to the minorities that their special religious freedoms will be maintained. If the BJP is going to go against that tacit understanding with the Indian minorities at the moment, they also have to consider the amount of disaffection that it is likely to bring to the various minorities. And India has a large number of minorities, not just Muslim. If they are going to force something that is basically a Hindu code of conduct on the other minorities, there is going to be internal resistance. Now, is it worthwhile imposing a uniform civil code which is going to create division within the Indian society? These are things that they will have to confront when they come to power and then they will have to evaluate whether taking these steps is of advantage, or whether not taking these rather provocative steps is of more benefit to them. So, this is what I mean by the realities of governance when you come to power.</FONT></BLOCKQUOTE>

<H4>AS: In that same regard, the <B>present prime minister in that interim period</B> when Nawaz Sharif was not Prime Minister, declared that Pakistan is indeed in possession of nuclear weapons. Do you think that Pakistan might consider a nuclear option if this issue is not resolved?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I don't think the nuclear option is a means of resolving the Kashmir issue. As I firmly believe, and I think most people who have looked at the Kashmir situation in any detail have come to the conclusion that the only way you can resolve it is through a dialogue with India, which also at a later state involves the Kashmiris. The situation, as I say, is that there is a population which is dissatisfied with the Indian governance. The Indian governance is no longer acceptable to them, and therefore they want a choice through a vote, through the exercise of their right either to accept or reject the Indian governance. And at some stage or other, the Indians will have to confront this situation. <P>

When I discuss this situation with the Indians, they say that the ground realities are that they have a very large security force in Kashmir and they have been able to contain the level of insurgency that is prevailing and they can continue to confront this level of insurgency for any number of years. One has to bring this to their notice, that ten years ago who would have thought that the Central Asians would become independent states? The Ukrainians were part of the present Soviet Union and the old Russia for 300 years and today they are an independent nation. The Georgians are an independent nation. The three Baltic states are independent states. The Belorussians are an independent state. So, if the Kashmiris are unwilling to be part of India, then I think historically at one time or the other, the Indians will have to part with them. It is only if the Kashmiris are willing to be part of the Indian Union, that they will be able to keep them. And I think this is the basic argument that we want to make, that there is no way that through brutality, through excessive use of military force, you can keep a people permanently subjugated if they are not willing to be part of India.</FONT></BLOCKQUOTE> 

<H4>AS: The US has recently condemned the atrocities being committed by the Indian Occupation Forces in the Kashmir valley. What steps do you think the United States should take to rectify this situation?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I think they can do a great deal more than they are doing at the moment. But not if they are going to depend solely on what they see as their own strategic interests in a particular region. Compare two countries, almost equal in size, namely China and India, one has a population of one billion, and the other has a population of 1.2 billion; so they are both very large countries, and they are both very important countries in Asia. Even if the Chinese get hold of a local dissident and put him in jail, the President of the United States is prepared to make a statement to ensure that he is treated fairly in jail, and finally when they are forced to release him, he goes to the United States. Here is a situation where it is not just putting a few people in jail. Fifty thousand people have been killed. They are fully aware of the number of women who are raped every day; the thousands of houses that have been burned, the children that have been killed. the people who have been taken into custody, then killed and their bodies thrown along the roadside. And this is happening every day. India is not seen as an adversary at the moment. China is not seen as an adversary, but it is a possible adversary in the future. And therefore China is dealt with differently than India because India is not considered an adversary at the moment. If India was seen as an adversary, you will find that the Americans would have come down much harder on the Indians because their violations have no comparison with what the Chinese are doing. But at the moment it is not part of the overall US policy to condemn India to an extent that it will turn from a partner into an adversary. India is also a possible future counter to the Chinese, if at any stage the Chinese become a major strategic problem, then here is a country that could confront that problem locally on behalf of the United States. So, for various strategic reasons, I think, the Indians get away with a great deal of what many other countries would not have been able to get away with. Primarily because of their size, because of the power and the influence that they wield.</FONT></BLOCKQUOTE>

<H4>AS: So, in very concrete terms, what can the United States do?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: It certainly could put the same kind of pressure on the Indians that it does on the Chinese. If it can force the Chinese to release individuals, it can certainly condemn and lead the crusade against these massive, I shouldn't say human rights violations really, because it makes the term very neutral. I mean, it is brutal and merciless use of military power against unarmed civilians. The US needs to condemn this much more openly and vigorously than it is doing at the moment. The Indians have always refused any international organization to go into Kashmir. Why do they refuse it? Because they know that the truth will then come out. They have never allowed Amnesty International to move into Kashmir so it can investigate firsthand all the allegations that have been made. So, at the moment they can say that these allegations are unproven because they won't allow anybody to go and investigate. I think the American administration and the human rights organizations could take a much more active interest in what is going on. And their active interest and their condemnation will certainly make a difference.</FONT></BLOCKQUOTE>

<H4>AS: What is Pakistan's relationship with Kashmir's most prominent Muslim leader, Mr. Shabir Shah? How does Pakistan support him?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: As you know, all of the Muslim leadership in Indian-occupied Kashmir, except those who are in support of the Indian government, which means the occupied Kashmir government of Farook Abdullah, all of the other Muslim political organizations have formed an umbrella organization which is called the All Parties Hurryat Conference. Hurryat means freedom struggle, so All Parties Freedom Struggle, we should say in English. Shabir Shah is also part of that organization, so the overall organization then coordinates the political activities of all its components, including his organization. And Pakistan is fully supportive of the activities of the All Parties Hurryat Conference because Pakistan's stand and belief is that they represent the genuine leadership in Indian-occupied Kashmir, and therefore, whatever this umbrella organization, which includes Shabir Shah, decides, is fully acceptable to Pakistan as the view of the Kashmiri people. The three sets of dialogue that Pakistan has had with India on Kashmir, every time we have briefed the All Parties Hurryat Conference leadership in detail that this is what we will discuss with the Indians and after the meeting we inform them as to what was the outcome of the discussion. So, we are keeping them fully informed through this umbrella organization of all the dialogue and discussion that is taking place.</FONT></BLOCKQUOTE>

<H4>AS: If the Jammu-Kashmir area opts for independence, what would be Pakistan's official stance and what would be its subjective stance?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I think you make a good distinction. That when we say that the UN Security Council Resolution ought to be implemented, the UN Security Council Resolution specifically stated that a plebiscite ought to be held in which the people of Kashmir can freely express their view whether they want to join Pakistan or they want to join India. Because this was the option that was given to all states of the Indian subcontinent at that time. There were over 600 states. Jammu and Kashmir was one of them. And all states with the exception of Jammu and Kashmir have exercised that right. The state of Jammu and Kashmir still hasn't.<P>

Now purely on a moral ground, I would say, that if the Kashmiris did want to opt for independence, I would see no harm in that at all. If you are talking of the implementation of the UN resolutions, then you'll either have to get those UN Security Council resolutions changed to include an independence clause, because under the present arrangements of the UN Security Council resolution, this option is not available to them. But I would personally say, that morally both India and Pakistan should feel obliged to support a choice of independence if the Kashmiris wanted that. Because if you're saying they should have a right of self-determination, that's self-determination today, 50 years after the resolution, and the Kashmiris may feel it's for them to be an independent state. So, I would find morally nothing wrong with that, if the majority of Kashmiris wanted that.<P>
 However, my own feeling is that this is something that the Western scholars primarily bring up to gauge the reaction of the Pakistanis. You take the happenings in occupied Kashmir, for example, yesterday... As you are fully aware, the Pakistanis have no control over Indian-occupied Kashmir. It has interaction with the Azad Kashmir government, but no interaction with the Indian-occupied Kashmir. Why do the Kashmiris under Indian occupation fly black flags on the Indian Independence Day and fly Pakistani flags on Pakistan Independence Day? I mean, if they want to be independent, who is asking them to fly the flags? On what basis, did they change their timing to Pakistan Standard Time yesterday? To conform with the Pakistani standard time. To indicate their solidarity with Pakistan. Therefore, it convinces us that even though this argument is being made, that it is not a valid argument. But I personally think that we should accept this choice, that if the Kashmiris really want to be independent, and they don't want to be any part of Pakistan, then Pakistan should not object to that.</FONT></BLOCKQUOTE> 

<H4> AS: What are the advantages for the Jammu-Kashmir area to become part of Pakistan rather than to choose independence?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: One, of course, is that it is a very small landlocked area. It has really three components if you only think of Indian-occupied Kashmir. It has the Jammu region which is predominantly Hindu, who have no desire to be independent of India, and therefore if an independent option was exercised certainly the people of Jammu would not want to be independent. There is the Ladakh region which geographically is a very large area but has a very small population. The majority of the population is Buddhist. Again that small Buddhist population with a substantive Muslim minority would have no reason to be independent because their economy is entirely dependent upon somebody else supporting them. And China next door to it, they would find it extremely hard to maintain an independent stance against three major states - Pakistan on one side and India on the other side and China on the third. That leaves the valley. <P>
Now my own view is that it has been the Indian view that if we cannot force the Kashmiris to remain a part of India, let's now start this third thing, that should, at least, not let them go to Pakistan. Let them be independent. I think we need to wait for the Kashmiris to decide for themselves. We need to ensure that the atmosphere and the environments are created where they are able to independently and fairly exercise their choice. And if in that scenario they opt for independence, well, so be it. But I see no indication of that except for the Indian propaganda or sometimes the Western scholars who I think make a moral point rather than a political point: what if the Kashmiris don't want to be part of Pakistan either? <P>
Now, the other point you made, what advantages would accrue to Kashmir? You look at the status of those Kashmiris who are now part of Pakistan, either through migration or otherwise being part of Pakistan. The present Prime Minister of Pakistan is a Kashmiri. Mr. Nawaz Sharif is a Kashmiri whose family migrated to Pakistan. A very large number who are very senior bureaucrats are of Kashmiri origin. Some still belong to Kashmir. One of my top scholars is a Kashmiri gentleman who migrated at the time of independence. Considering the opportunity that they are likely to have in Pakistan, both in terms of personal advancement and in terms of their status in the world community, I don't see any Kashmiri who would find it of advantage to be from a small, landlocked bit of four million people which is surrounded on all sides by one would say unfriendly powers. Because if they opt out of India, India is not going to be very friendly. If they opt out of Pakistan, probably it would be less inimical towards them, but not too pleased with their choice. On the third side is China which the Indians claim has already taken a lot of the territory as part of China. So, what advantage would accrue?</FONT></BLOCKQUOTE>

<H4>AS: If it does become part of Pakistan officially, how then would Pakistan deal with the Hindu separatist movement that is calling for its own state?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I think the plebiscite will have to take the realities into account. My personal view is that even though most Kashmiris want the whole state to go through a plebiscite and since the Muslims are in majority, therefore, the majority view is going to be for Pakistan. But it does not take into account the geographical and the communal reality of a particular part of the state being a Hindu majority. And I think it will be fair to allow this geographical element to exercise an independent choice. I don't think most Kashmiris would agree with it. They would want the whole state to decide. It appears to me almost certain that if the state as a whole decided, then the majority would vote for Pakistan which would force Jammu which is a Hindu majority area, to become part of Pakistan which I think may not be a realistic solution and therefore, I think we ought to consider the option of Jammu joining the Indian Union rather than becoming a part of Pakistan.</FONT></BLOCKQUOTE>

<H4>AS: Recently a summit was held by <B>the Organization of Islamic Conference</B>, the OIC in Tehran. There an economic boycott of India was urged. Do you support this move? Is this intelligent?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: It may be part of the rhetoric that is raised at the OIC. I don't think an economic boycott firstly is feasible, and secondly I don't think that it has worked anywhere else. Even when much greater willingness was behind the states wanting to impose sanctions on various countries. It has never seemed to have succeeded. Secondly, I don't think most Muslim countries would want to take that major a step to support Pakistan in terms of its approach to the Kashmir problem. I mean, we would probably be justified having India condemned in the OIC because of the massive brutality that they are inflicting on a civilian population, but I don't think the economic boycott is a realistic option. I don't think you would find too many people who would be supportive of this because their own interests would also suffer.</FONT></BLOCKQUOTE>

<H4>AS: Well, what measures do you think should be taken to further international understanding of the issue. I think as we were discussing before, the Americans, and the Japanese remain fairly ignorant of the present situation. What measures do you think could be taken to further highlight the problem?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: I think we need to start highlighting the problem that exists in Kashmir. And the problem is the coercive use of a very large security force to subjugate a hapless population, rather than project this primarily as a UN resolution that has still not been implemented. I think this is our main problem. The Indian governance is now subjecting Kashmiris to untold brutalities. You need to inform the Indians that you talk of your democracy, the largest functioning democracy, but a democracy does not subjugate people to military force. It convinces its own population to willingly participate in this democratic process. And if a community is so unwilling after 50 years of your democratic experience that they no longer want to be part of you, then you need to reconsider your options. You cannot keep a people permanently part of you through the use of military force. This is too expensive an option for you and an unacceptable option for the rest of the world. <P>

The point that I want to make is that Indians talk of their democracy. I have challenged many Indians that you give me any period of six months in your entire history of fifty years when your military has not been oppressively deployed against your own people. What kind of democracy do you have where your armed forces are permanently being used operationally against one part of your population or the other? I can't think of any other democracy or even autocracy or dictatorship where the military is constantly being used against its own population. Here is a so-called democracy that has constantly used its military power against its own people. There are over 600,000 security forces deployed in Kashmir. As you are aware, the total population of the valley is 4.2 million. So you have a population of 4.2 million where you have 600,000 security forces deployed to keep this under control and that gives you a ratio of one soldier to seven persons. Those seven persons include the new-born baby and the dying old man. It's not against the adult population of the valley, it's the total population of the valley. <P>
I think this is a situation which is unacceptable. And these security forces that you have deployed there have caused suffering that would be outrageous even for a dictatorship; that their actions cannot be challenged in a court; that their actions can not be challenged even in the Human Rights Commission of the Indians itself; that they are not accountable to the political government in the State for their actions. They work totally outside the authority of the political government. Why does the rest of the world permit this situation to carry on and not object? They would strenuously object even if the situation was say three times better than Kashmir any where else. But since the large Indian market seems to be so attractive to the rest of the world, therefore it is prepared to look the other way when the Indians do all of this. The only way you can make sure that the world realizes is to take the case of Bosnia. I think there is one individual who forced if not the Europeans, then certainly the United States to recognize and that one person was Christiana Amanpour, merely by her coverage of the Bosnian situation on CNN. She forced the American government to act. Just one person. Who wll be that person for Kashmir?</FONT></BLOCKQUOTE>

<H4>AS: February 5th is Kashmir Independence Day. Could you tell us what that represents, what it symbolizes here in Pakistan?</H4>

<BLOCKQUOTE><FONT  SIZE=+1><STRONG>NA</STRONG>: This is what we call the day of solidarity with the Kashmiri struggle. You'll find that in the body politic of Pakistan, there are a great number of divisions, like there are in every other country -- like the Republicans can't stand the Democrats and the Democrats can't stand the Republicans in the United States. But this is an issue on which all political elements in Pakistan are united in terms of their support for the Kashmiri struggle, whether that person belongs to the Pakistan People's Party or is part of the Sindhi Nationalist Party in Sindh or whatever. They demonstrably express their support for the Kashmiri struggle on this day to give moral, political and diplomatic support to the Kashmiri struggle and to emphasize that they are not alone in their struggle, that Pakistan is willing to support you in every manner which is possible.

And when I say every manner it doesn't talk of military support because, as I said earlier on, I don't think the military is the final solution. For the Kashmiris of course this is one way of expressing their dissatisfaction with the Indian governance, that some of them have taken up arms; the others are continuing their struggle under the leadership of the All Parties Hurryat Conference. And this day was really to indicate to the APHC that through you we want to convey to the people of Kashmir that all of Pakistan is fully supportive of your political struggle to throw the Indian yoke away.</FONT><P>

<STRONG>Interviewed by: Arlyn Starr</STRONG><BR>Islamabad, February 13, 1998
</BLOCKQUOTE>

<CENTER>

<IMG src="/graph/fdline5.gif" WIDTH=250 HEIGHT=4 VSPACE=9><BR>
<A HREF="../fdlalert.html"><STRONG>Back to Alerts</A></STRONG> | 
<A HREF="../fdlpaper.html#interview"><STRONG>Main Archives</A></STRONG><BR>

<IMG src="/graph/fdline5.gif" WIDTH=250 HEIGHT=4 VSPACE=9><BR>
<P>
</CENTER>
<FONT  SIZE=2><A HREF="mailto:Secretariat@fdlap.org"><STRONG><U>Contact FDLAP...</U></STRONG></A><BR>
<A HREF="fdlorg.html#address">Our Address...</A></FONT>
<HR WIDTH=105 ALIGN=LEFT SIZE=2>
<FONT  SIZE=-2 COLOR=#007339>Pagework by Nancho East</FONT>


`;

  return (
    <div className="fdl-page min-h-screen p-4 md:p-8">
      <div className="fdl-container">
        <SafeHtml html={htmlContent} className="fdl-content w-full" />
        
        {/* Simple back navigation footer */}
        <center className="w-full mt-12 pt-6 border-t border-[#003E1F]/10">
          <Link to="/" className="text-[#007339] underline font-bold hover:text-[#1866C5] text-sm md:text-base">
            Back to Home
          </Link>
        </center>
      </div>
    </div>
  );
};

export default KashmirNahmad;
